### ISSUE TITLE
权重文件

### ISSUE THREAD

**Issue by LmYy555** [remaro-network/KD-YOLOX-ViT#2]
您好，我想问下，就是您的权重pth在哪里呢，我找了很长时间，没有找到。

**Comment by 2609780105** [comment]
可以给一下您的预训练权重文件吗，我想先demo一下。

**Comment by LmYy555** [comment]
可以给一下您的预训练权重文件吗，我想先demo一下。2609780105@qq.com

**Comment by martinaub** [comment]
Hi @2609780105. Sorry for the delay. I have updated the README.md, you can find a table with the weights used for our paper. Please let me know if you have a problem for using them :)
